// Extended Companies Database - Part 2
// More Tech Companies, Startups, and MNCs

const COMPANIES_DATABASE_2 = [
    // ==================== MORE FAANG & BIG TECH ====================
    {name: "Nvidia", type: "PRODUCT", category: "BIG_TECH", desc: "GPU and AI computing leader", hq: "USA", india: ["Bangalore", "Pune", "Hyderabad"], remote: true, hiring: true, salary: "₹30-90 LPA", culture: 4.5, wlb: 4.0, interview: 4.5, careers: "https://nvidia.com/careers", employees: "26K+", founded: 1993, tech: ["CUDA", "C++", "Python", "Deep Learning"]},
    {name: "Intel", type: "PRODUCT", category: "BIG_TECH", desc: "Semiconductor and computing technology", hq: "USA", india: ["Bangalore", "Hyderabad"], remote: true, hiring: true, salary: "₹18-60 LPA", culture: 4.0, wlb: 4.2, interview: 4.0, careers: "https://intel.com/jobs", employees: "130K+", founded: 1968, tech: ["C++", "Python", "FPGA", "Hardware"]},
    {name: "AMD", type: "PRODUCT", category: "BIG_TECH", desc: "Semiconductor company", hq: "USA", india: ["Bangalore", "Hyderabad"], remote: true, hiring: true, salary: "₹18-55 LPA", culture: 4.0, wlb: 4.0, interview: 4.0, careers: "https://amd.com/careers", employees: "25K+", founded: 1969, tech: ["C++", "Verilog", "Python", "GPU"]},
    {name: "Qualcomm", type: "PRODUCT", category: "BIG_TECH", desc: "Wireless technology and semiconductors", hq: "USA", india: ["Bangalore", "Hyderabad", "Chennai"], remote: true, hiring: true, salary: "₹18-60 LPA", culture: 4.0, wlb: 4.0, interview: 4.2, careers: "https://qualcomm.com/company/careers", employees: "45K+", founded: 1985, tech: ["C++", "5G", "ML", "Embedded"]},
    {name: "Cisco", type: "PRODUCT", category: "BIG_TECH", desc: "Networking and cybersecurity", hq: "USA", india: ["Bangalore", "Chennai", "Pune"], remote: true, hiring: true, salary: "₹15-50 LPA", culture: 4.0, wlb: 4.2, interview: 3.8, careers: "https://cisco.com/careers", employees: "80K+", founded: 1984, tech: ["Python", "Networking", "Security", "Cloud"]},
    {name: "VMware", type: "PRODUCT", category: "BIG_TECH", desc: "Virtualization and cloud infrastructure", hq: "USA", india: ["Bangalore", "Pune"], remote: true, hiring: true, salary: "₹18-55 LPA", culture: 4.2, wlb: 4.0, interview: 4.0, careers: "https://careers.vmware.com", employees: "35K+", founded: 1998, tech: ["Go", "Python", "Kubernetes", "Cloud"]},
    {name: "ServiceNow", type: "PRODUCT", category: "BIG_TECH", desc: "Digital workflow platform", hq: "USA", india: ["Hyderabad", "Bangalore"], remote: true, hiring: true, salary: "₹18-55 LPA", culture: 4.2, wlb: 4.0, interview: 4.0, careers: "https://servicenow.com/careers", employees: "20K+", founded: 2004, tech: ["JavaScript", "Python", "Java", "Cloud"]},
    {name: "Workday", type: "PRODUCT", category: "BIG_TECH", desc: "Enterprise cloud applications for HR and finance", hq: "USA", india: ["Bangalore", "Pune"], remote: true, hiring: true, salary: "₹18-55 LPA", culture: 4.3, wlb: 4.2, interview: 3.8, careers: "https://workday.com/careers", employees: "17K+", founded: 2005, tech: ["Java", "Python", "React", "Cloud"]},
    {name: "Palo Alto Networks", type: "PRODUCT", category: "BIG_TECH", desc: "Cybersecurity company", hq: "USA", india: ["Bangalore"], remote: true, hiring: true, salary: "₹20-60 LPA", culture: 4.2, wlb: 3.8, interview: 4.2, careers: "https://paloaltonetworks.com/careers", employees: "13K+", founded: 2005, tech: ["Python", "Go", "Security", "Cloud"]},
    {name: "CrowdStrike", type: "PRODUCT", category: "BIG_TECH", desc: "Cybersecurity technology", hq: "USA", india: ["Pune"], remote: true, hiring: true, salary: "₹20-60 LPA", culture: 4.3, wlb: 4.0, interview: 4.0, careers: "https://crowdstrike.com/careers", employees: "8K+", founded: 2011, tech: ["Go", "Python", "C++", "Security"]},
    {name: "Splunk", type: "PRODUCT", category: "BIG_TECH", desc: "Data platform for security and observability", hq: "USA", india: ["Bangalore", "Hyderabad"], remote: true, hiring: true, salary: "₹20-55 LPA", culture: 4.2, wlb: 4.0, interview: 4.0, careers: "https://splunk.com/careers", employees: "8K+", founded: 2003, tech: ["Python", "Java", "React", "Big Data"]},
    {name: "Autodesk", type: "PRODUCT", category: "BIG_TECH", desc: "3D design and engineering software", hq: "USA", india: ["Bangalore", "Pune"], remote: true, hiring: true, salary: "₹15-50 LPA", culture: 4.0, wlb: 4.2, interview: 3.8, careers: "https://autodesk.com/careers", employees: "13K+", founded: 1982, tech: ["C++", "Python", "3D", "Cloud"]},
    {name: "Intuit", type: "PRODUCT", category: "BIG_TECH", desc: "Financial software (TurboTax, QuickBooks)", hq: "USA", india: ["Bangalore"], remote: true, hiring: true, salary: "₹20-60 LPA", culture: 4.3, wlb: 4.2, interview: 4.0, careers: "https://intuit.com/careers", employees: "17K+", founded: 1983, tech: ["Java", "Python", "React", "AWS"]},
    {name: "DocuSign", type: "PRODUCT", category: "BIG_TECH", desc: "Electronic signature and agreement cloud", hq: "USA", india: ["Bangalore"], remote: true, hiring: true, salary: "₹18-50 LPA", culture: 4.2, wlb: 4.2, interview: 3.8, careers: "https://docusign.com/careers", employees: "7K+", founded: 2003, tech: ["Java", "Python", "React", "AWS"]},
    {name: "Zoom", type: "PRODUCT", category: "BIG_TECH", desc: "Video communications platform", hq: "USA", india: ["Bangalore"], remote: true, hiring: true, salary: "₹20-55 LPA", culture: 4.2, wlb: 4.0, interview: 4.0, careers: "https://zoom.us/careers", employees: "8K+", founded: 2011, tech: ["C++", "Python", "React", "WebRTC"]},
    {name: "Okta", type: "PRODUCT", category: "BIG_TECH", desc: "Identity and access management", hq: "USA", india: ["Bangalore"], remote: true, hiring: true, salary: "₹20-55 LPA", culture: 4.2, wlb: 4.0, interview: 4.0, careers: "https://okta.com/careers", employees: "6K+", founded: 2009, tech: ["Java", "Go", "React", "Security"]},
    {name: "Cloudflare", type: "PRODUCT", category: "BIG_TECH", desc: "Web performance and security", hq: "USA", india: ["Remote"], remote: true, hiring: true, salary: "₹22-60 LPA", culture: 4.4, wlb: 4.2, interview: 4.2, careers: "https://cloudflare.com/careers", employees: "3K+", founded: 2009, tech: ["Go", "Rust", "JavaScript", "Network"]},
    {name: "Akamai", type: "PRODUCT", category: "BIG_TECH", desc: "Content delivery and cloud security", hq: "USA", india: ["Bangalore"], remote: true, hiring: true, salary: "₹15-50 LPA", culture: 4.0, wlb: 4.0, interview: 3.8, careers: "https://akamai.com/careers", employees: "10K+", founded: 1998, tech: ["C++", "Python", "Go", "CDN"]},
    {name: "Red Hat", type: "PRODUCT", category: "BIG_TECH", desc: "Enterprise open source software", hq: "USA", india: ["Bangalore", "Pune"], remote: true, hiring: true, salary: "₹15-50 LPA", culture: 4.3, wlb: 4.2, interview: 3.8, careers: "https://redhat.com/jobs", employees: "20K+", founded: 1993, tech: ["Linux", "Kubernetes", "Ansible", "Python"]},
    {name: "GitHub", type: "PRODUCT", category: "BIG_TECH", desc: "Software development platform", hq: "USA", india: ["Remote"], remote: true, hiring: true, salary: "₹25-70 LPA", culture: 4.5, wlb: 4.3, interview: 4.2, careers: "https://github.com/about/careers", employees: "3K+", founded: 2008, tech: ["Ruby", "Go", "TypeScript", "React"]},
    {name: "GitLab", type: "PRODUCT", category: "UNICORN", desc: "DevOps platform", hq: "USA", india: ["Remote"], remote: true, hiring: true, salary: "₹25-65 LPA", culture: 4.5, wlb: 4.5, interview: 4.0, careers: "https://gitlab.com/jobs", employees: "2K+", founded: 2011, tech: ["Ruby", "Go", "Vue.js", "Kubernetes"]},
    
    // ==================== MORE INDIAN UNICORNS & STARTUPS ====================
    {name: "Zepto", type: "PRODUCT", category: "INDIAN_UNICORN", desc: "Quick commerce - 10 min delivery", hq: "India", india: ["Mumbai", "Bangalore"], remote: true, hiring: true, salary: "₹18-55 LPA", culture: 3.8, wlb: 3.0, interview: 4.0, careers: "https://zepto.com/careers", employees: "3K+", founded: 2021, tech: ["Python", "React Native", "Node.js", "AWS"]},
    {name: "Blinkit", type: "PRODUCT", category: "INDIAN_UNICORN", desc: "Quick commerce platform", hq: "India", india: ["Gurgaon", "Bangalore"], remote: true, hiring: true, salary: "₹15-50 LPA", culture: 3.5, wlb: 3.0, interview: 3.8, careers: "https://blinkit.com/careers", employees: "2K+", founded: 2013, tech: ["Python", "React", "Node.js", "AWS"]},
    {name: "Nykaa", type: "PRODUCT", category: "INDIAN_UNICORN", desc: "Beauty and fashion e-commerce", hq: "India", india: ["Mumbai", "Bangalore"], remote: true, hiring: true, salary: "₹12-45 LPA", culture: 3.8, wlb: 3.5, interview: 3.5, careers: "https://nykaa.com/careers", employees: "3K+", founded: 2012, tech: ["Python", "React", "Node.js", "AWS"]},
    {name: "Rapido", type: "PRODUCT", category: "INDIAN_UNICORN", desc: "Bike taxi and auto booking", hq: "India", india: ["Bangalore"], remote: true, hiring: true, salary: "₹12-40 LPA", culture: 3.8, wlb: 3.5, interview: 3.5, careers: "https://rapido.bike/careers", employees: "1K+", founded: 2015, tech: ["Python", "React Native", "Node.js"]},
    {name: "Slice", type: "PRODUCT", category: "INDIAN_UNICORN", desc: "Credit card and payments", hq: "India", india: ["Bangalore"], remote: true, hiring: true, salary: "₹18-50 LPA", culture: 4.0, wlb: 3.5, interview: 4.0, careers: "https://sliceit.com/careers", employees: "1K+", founded: 2016, tech: ["Go", "React Native", "Python", "AWS"]},
    {name: "Jupiter", type: "PRODUCT", category: "STARTUP", desc: "Digital banking app", hq: "India", india: ["Bangalore"], remote: true, hiring: true, salary: "₹18-50 LPA", culture: 4.2, wlb: 3.8, interview: 4.0, careers: "https://jupiter.money/careers", employees: "500+", founded: 2019, tech: ["Kotlin", "Swift", "Python", "AWS"]},
    {name: "Fi Money", type: "PRODUCT", category: "STARTUP", desc: "Neobank for millennials", hq: "India", india: ["Bangalore"], remote: true, hiring: true, salary: "₹18-50 LPA", culture: 4.2, wlb: 3.8, interview: 4.0, careers: "https://fi.money/careers", employees: "300+", founded: 2019, tech: ["Kotlin", "Swift", "Go", "AWS"]},
    {name: "Delhivery", type: "PRODUCT", category: "INDIAN_UNICORN", desc: "Logistics and supply chain", hq: "India", india: ["Gurgaon", "Bangalore"], remote: true, hiring: true, salary: "₹12-40 LPA", culture: 3.5, wlb: 3.2, interview: 3.5, careers: "https://delhivery.com/careers", employees: "5K+", founded: 2011, tech: ["Python", "Java", "React", "AWS"]},
    {name: "Shiprocket", type: "PRODUCT", category: "STARTUP", desc: "E-commerce shipping platform", hq: "India", india: ["Delhi", "Bangalore"], remote: true, hiring: true, salary: "₹10-35 LPA", culture: 3.8, wlb: 3.5, interview: 3.5, careers: "https://shiprocket.com/careers", employees: "1K+", founded: 2017, tech: ["Python", "React", "Node.js", "AWS"]},
    {name: "INDmoney", type: "PRODUCT", category: "STARTUP", desc: "Investment and finance app", hq: "India", india: ["Gurgaon"], remote: true, hiring: true, salary: "₹15-45 LPA", culture: 4.0, wlb: 3.5, interview: 4.0, careers: "https://indmoney.com/careers", employees: "500+", founded: 2019, tech: ["Python", "React Native", "Node.js"]},
    {name: "Upstox", type: "PRODUCT", category: "INDIAN_UNICORN", desc: "Stock trading platform", hq: "India", india: ["Mumbai", "Bangalore"], remote: true, hiring: true, salary: "₹15-50 LPA", culture: 4.0, wlb: 3.8, interview: 4.0, careers: "https://upstox.com/careers", employees: "1.5K+", founded: 2012, tech: ["Java", "React", "Python", "AWS"]},
    {name: "Angel One", type: "PRODUCT", category: "STARTUP", desc: "Stock broking and trading", hq: "India", india: ["Mumbai", "Bangalore"], remote: true, hiring: true, salary: "₹12-40 LPA", culture: 3.8, wlb: 3.5, interview: 3.8, careers: "https://angelone.in/careers", employees: "2K+", founded: 1996, tech: ["Java", "React", "Python", "AWS"]},
    {name: "Paytm Money", type: "PRODUCT", category: "STARTUP", desc: "Investment platform", hq: "India", india: ["Noida", "Bangalore"], remote: true, hiring: true, salary: "₹12-40 LPA", culture: 3.5, wlb: 3.5, interview: 3.5, careers: "https://paytmmoney.com/careers", employees: "500+", founded: 2018, tech: ["Java", "React Native", "Python"]},
    {name: "Instamojo", type: "PRODUCT", category: "STARTUP", desc: "Payment gateway for SMBs", hq: "India", india: ["Bangalore"], remote: true, hiring: true, salary: "₹12-40 LPA", culture: 4.0, wlb: 4.0, interview: 3.5, careers: "https://instamojo.com/careers", employees: "400+", founded: 2012, tech: ["Python", "Django", "React", "AWS"]},
    {name: "Cashfree", type: "PRODUCT", category: "STARTUP", desc: "Payment gateway and banking", hq: "India", india: ["Bangalore"], remote: true, hiring: true, salary: "₹15-45 LPA", culture: 4.0, wlb: 3.8, interview: 3.8, careers: "https://cashfree.com/careers", employees: "500+", founded: 2015, tech: ["Go", "Python", "React", "AWS"]},
    {name: "Juspay", type: "PRODUCT", category: "STARTUP", desc: "Payment orchestration platform", hq: "India", india: ["Bangalore"], remote: true, hiring: true, salary: "₹18-50 LPA", culture: 4.2, wlb: 4.0, interview: 4.2, careers: "https://juspay.in/careers", employees: "500+", founded: 2012, tech: ["Haskell", "PureScript", "React", "AWS"]},
    {name: "Pine Labs", type: "PRODUCT", category: "INDIAN_UNICORN", desc: "POS and payment solutions", hq: "India", india: ["Noida", "Bangalore"], remote: true, hiring: true, salary: "₹15-45 LPA", culture: 4.0, wlb: 3.8, interview: 3.8, careers: "https://pinelabs.com/careers", employees: "2K+", founded: 1998, tech: ["Java", "Python", "React", "AWS"]},
    {name: "MoEngage", type: "PRODUCT", category: "STARTUP", desc: "Customer engagement platform", hq: "India", india: ["Bangalore"], remote: true, hiring: true, salary: "₹15-50 LPA", culture: 4.2, wlb: 4.0, interview: 4.0, careers: "https://moengage.com/careers", employees: "600+", founded: 2014, tech: ["Java", "Python", "React", "AWS"]},
    {name: "CleverTap", type: "PRODUCT", category: "STARTUP", desc: "Customer engagement and retention", hq: "India", india: ["Mumbai", "Bangalore"], remote: true, hiring: true, salary: "₹15-50 LPA", culture: 4.0, wlb: 3.8, interview: 4.0, careers: "https://clevertap.com/careers", employees: "600+", founded: 2013, tech: ["Java", "Python", "React", "AWS"]},
    {name: "WebEngage", type: "PRODUCT", category: "STARTUP", desc: "Marketing automation platform", hq: "India", india: ["Mumbai"], remote: true, hiring: true, salary: "₹12-40 LPA", culture: 4.0, wlb: 3.8, interview: 3.8, careers: "https://webengage.com/careers", employees: "400+", founded: 2011, tech: ["Java", "Python", "React", "AWS"]},
    {name: "LeadSquared", type: "PRODUCT", category: "STARTUP", desc: "CRM and marketing automation", hq: "India", india: ["Bangalore"], remote: true, hiring: true, salary: "₹10-35 LPA", culture: 3.8, wlb: 3.5, interview: 3.5, careers: "https://leadsquared.com/careers", employees: "1K+", founded: 2012, tech: ["Java", ".NET", "React", "AWS"]},
    {name: "Druva", type: "PRODUCT", category: "INDIAN_UNICORN", desc: "Cloud data protection", hq: "India", india: ["Pune"], remote: true, hiring: true, salary: "₹18-55 LPA", culture: 4.2, wlb: 4.0, interview: 4.0, careers: "https://druva.com/careers", employees: "1K+", founded: 2008, tech: ["Python", "Go", "AWS", "Cloud"]},
    {name: "Hasura", type: "PRODUCT", category: "STARTUP", desc: "GraphQL API platform", hq: "India", india: ["Bangalore"], remote: true, hiring: true, salary: "₹20-55 LPA", culture: 4.5, wlb: 4.3, interview: 4.2, careers: "https://hasura.io/careers", employees: "200+", founded: 2017, tech: ["Haskell", "Go", "React", "GraphQL"]},
    {name: "Frappe", type: "PRODUCT", category: "STARTUP", desc: "ERPNext and Frappe Framework", hq: "India", india: ["Mumbai"], remote: true, hiring: true, salary: "₹8-30 LPA", culture: 4.5, wlb: 4.5, interview: 3.5, careers: "https://frappe.io/careers", employees: "100+", founded: 2008, tech: ["Python", "JavaScript", "MariaDB"]},
    {name: "Zoho", type: "PRODUCT", category: "PRODUCT", desc: "Business software suite", hq: "India", india: ["Chennai", "Bangalore"], remote: true, hiring: true, salary: "₹8-35 LPA", culture: 4.0, wlb: 4.2, interview: 3.8, careers: "https://zoho.com/careers", employees: "15K+", founded: 1996, tech: ["Java", "Python", "JavaScript", "Cloud"]},
    {name: "Turing", type: "PRODUCT", category: "STARTUP", desc: "Remote developer platform", hq: "USA", india: ["Remote"], remote: true, hiring: true, salary: "₹25-80 LPA", culture: 4.2, wlb: 4.5, interview: 4.0, careers: "https://turing.com/jobs", employees: "2K+", founded: 2018, tech: ["Python", "React", "Node.js", "AWS"]},
    {name: "Thoughtworks", type: "SERVICE", category: "CONSULTING", desc: "Technology consulting", hq: "USA", india: ["Bangalore", "Pune", "Chennai", "Hyderabad", "Gurgaon"], remote: true, hiring: true, salary: "₹12-45 LPA", culture: 4.5, wlb: 4.0, interview: 4.2, careers: "https://thoughtworks.com/careers", employees: "12K+", founded: 1993, tech: ["Java", "Python", "React", "Agile"]},
    
    // ==================== GLOBAL PRODUCT COMPANIES ====================
    {name: "Palantir", type: "PRODUCT", category: "BIG_TECH", desc: "Data analytics software", hq: "USA", india: ["Remote"], remote: true, hiring: true, salary: "₹35-90 LPA", culture: 4.0, wlb: 3.2, interview: 4.8, careers: "https://palantir.com/careers", employees: "3K+", founded: 2003, tech: ["Java", "Python", "Go", "Big Data"]},
    {name: "Snowflake", type: "PRODUCT", category: "UNICORN", desc: "Cloud data platform", hq: "USA", india: ["Bangalore"], remote: true, hiring: true, salary: "₹30-80 LPA", culture: 4.3, wlb: 4.0, interview: 4.3, careers: "https://snowflake.com/careers", employees: "6K+", founded: 2012, tech: ["Java", "Python", "SQL", "Cloud"]},
    {name: "Rubrik", type: "PRODUCT", category: "UNICORN", desc: "Cloud data management", hq: "USA", india: ["Bangalore", "Pune"], remote: true, hiring: true, salary: "₹25-65 LPA", culture: 4.2, wlb: 4.0, interview: 4.2, careers: "https://rubrik.com/careers", employees: "3K+", founded: 2014, tech: ["Go", "Python", "React", "Cloud"]},
    {name: "Cohesity", type: "PRODUCT", category: "UNICORN", desc: "Data management platform", hq: "USA", india: ["Bangalore", "Pune"], remote: true, hiring: true, salary: "₹22-60 LPA", culture: 4.0, wlb: 4.0, interview: 4.0, careers: "https://cohesity.com/careers", employees: "2K+", founded: 2013, tech: ["Go", "Python", "React", "Cloud"]},
    {name: "Nutanix", type: "PRODUCT", category: "BIG_TECH", desc: "Hybrid cloud infrastructure", hq: "USA", india: ["Bangalore", "Pune"], remote: true, hiring: true, salary: "₹18-55 LPA", culture: 4.0, wlb: 4.0, interview: 4.0, careers: "https://nutanix.com/careers", employees: "7K+", founded: 2009, tech: ["Python", "Go", "C++", "Cloud"]},
    {name: "Commvault", type: "PRODUCT", category: "BIG_TECH", desc: "Data management solutions", hq: "USA", india: ["Hyderabad"], remote: true, hiring: true, salary: "₹15-45 LPA", culture: 3.8, wlb: 4.0, interview: 3.8, careers: "https://commvault.com/careers", employees: "3K+", founded: 1996, tech: ["Java", "C++", "Python", "Cloud"]},
    {name: "NetApp", type: "PRODUCT", category: "BIG_TECH", desc: "Data storage and cloud services", hq: "USA", india: ["Bangalore"], remote: true, hiring: true, salary: "₹15-50 LPA", culture: 4.0, wlb: 4.2, interview: 3.8, careers: "https://netapp.com/careers", employees: "12K+", founded: 1992, tech: ["C", "Python", "Go", "Storage"]},
    {name: "Pure Storage", type: "PRODUCT", category: "UNICORN", desc: "All-flash data storage", hq: "USA", india: ["Bangalore"], remote: true, hiring: true, salary: "₹20-55 LPA", culture: 4.2, wlb: 4.0, interview: 4.0, careers: "https://purestorage.com/careers", employees: "5K+", founded: 2009, tech: ["Python", "Go", "C++", "Storage"]},
    {name: "Confluent", type: "PRODUCT", category: "UNICORN", desc: "Data streaming platform", hq: "USA", india: ["Bangalore"], remote: true, hiring: true, salary: "₹25-70 LPA", culture: 4.3, wlb: 4.0, interview: 4.2, careers: "https://confluent.io/careers", employees: "3K+", founded: 2014, tech: ["Java", "Kafka", "Python", "Go"]},
    {name: "DigitalOcean", type: "PRODUCT", category: "UNICORN", desc: "Cloud infrastructure provider", hq: "USA", india: ["Bangalore"], remote: true, hiring: true, salary: "₹18-50 LPA", culture: 4.3, wlb: 4.2, interview: 3.8, careers: "https://digitalocean.com/careers", employees: "1K+", founded: 2011, tech: ["Go", "Python", "Kubernetes", "Cloud"]},
    {name: "Linode (Akamai)", type: "PRODUCT", category: "BIG_TECH", desc: "Cloud hosting provider", hq: "USA", india: ["Remote"], remote: true, hiring: true, salary: "₹18-50 LPA", culture: 4.2, wlb: 4.3, interview: 3.8, careers: "https://linode.com/careers", employees: "500+", founded: 2003, tech: ["Python", "Go", "Linux", "Cloud"]},
    {name: "Hetzner", type: "PRODUCT", category: "PRODUCT", desc: "Web hosting and cloud", hq: "Germany", india: ["Remote"], remote: true, hiring: false, salary: "₹15-40 LPA", culture: 4.0, wlb: 4.5, interview: 3.5, careers: "https://hetzner.com/careers", employees: "300+", founded: 1997, tech: ["Linux", "Python", "Go", "Cloud"]},
    {name: "Render", type: "PRODUCT", category: "STARTUP", desc: "Cloud application platform", hq: "USA", india: ["Remote"], remote: true, hiring: true, salary: "₹25-60 LPA", culture: 4.5, wlb: 4.3, interview: 4.0, careers: "https://render.com/careers", employees: "100+", founded: 2018, tech: ["Go", "Ruby", "React", "Kubernetes"]},
    {name: "Railway", type: "PRODUCT", category: "STARTUP", desc: "Infrastructure platform", hq: "USA", india: ["Remote"], remote: true, hiring: true, salary: "₹25-60 LPA", culture: 4.5, wlb: 4.5, interview: 4.0, careers: "https://railway.app/careers", employees: "50+", founded: 2020, tech: ["Go", "Rust", "TypeScript", "Kubernetes"]},
    {name: "Fly.io", type: "PRODUCT", category: "STARTUP", desc: "Application deployment platform", hq: "USA", india: ["Remote"], remote: true, hiring: true, salary: "₹25-60 LPA", culture: 4.5, wlb: 4.5, interview: 4.0, careers: "https://fly.io/jobs", employees: "50+", founded: 2017, tech: ["Go", "Elixir", "Rust", "Kubernetes"]},
    {name: "PlanetScale", type: "PRODUCT", category: "STARTUP", desc: "Serverless MySQL platform", hq: "USA", india: ["Remote"], remote: true, hiring: true, salary: "₹30-70 LPA", culture: 4.5, wlb: 4.3, interview: 4.2, careers: "https://planetscale.com/careers", employees: "100+", founded: 2018, tech: ["Go", "MySQL", "Vitess", "Kubernetes"]},
    {name: "Neon", type: "PRODUCT", category: "STARTUP", desc: "Serverless Postgres", hq: "USA", india: ["Remote"], remote: true, hiring: true, salary: "₹30-70 LPA", culture: 4.5, wlb: 4.3, interview: 4.2, careers: "https://neon.tech/careers", employees: "100+", founded: 2021, tech: ["Rust", "PostgreSQL", "Go", "Cloud"]},
    {name: "Turso", type: "PRODUCT", category: "STARTUP", desc: "Edge database platform", hq: "USA", india: ["Remote"], remote: true, hiring: true, salary: "₹25-60 LPA", culture: 4.5, wlb: 4.5, interview: 4.0, careers: "https://turso.tech/careers", employees: "50+", founded: 2022, tech: ["Rust", "SQLite", "Go"]},
    
    // ==================== E-COMMERCE & RETAIL ====================
    {name: "Myntra", type: "PRODUCT", category: "PRODUCT", desc: "Fashion e-commerce", hq: "India", india: ["Bangalore"], remote: true, hiring: true, salary: "₹15-50 LPA", culture: 3.8, wlb: 3.5, interview: 4.0, careers: "https://myntra.com/careers", employees: "5K+", founded: 2007, tech: ["Java", "React", "Python", "AWS"]},
    {name: "Ajio", type: "PRODUCT", category: "PRODUCT", desc: "Fashion e-commerce by Reliance", hq: "India", india: ["Mumbai", "Bangalore"], remote: true, hiring: true, salary: "₹12-40 LPA", culture: 3.5, wlb: 3.5, interview: 3.5, careers: "https://ajio.com/careers", employees: "2K+", founded: 2016, tech: ["Java", "React", "Python", "AWS"]},
    {name: "Tata CLiQ", type: "PRODUCT", category: "PRODUCT", desc: "Multi-category e-commerce", hq: "India", india: ["Mumbai", "Bangalore"], remote: true, hiring: true, salary: "₹12-40 LPA", culture: 3.8, wlb: 3.8, interview: 3.5, careers: "https://tatacliq.com/careers", employees: "1K+", founded: 2016, tech: ["Java", "React", "Python", "AWS"]},
    {name: "BigBasket", type: "PRODUCT", category: "PRODUCT", desc: "Online grocery delivery", hq: "India", india: ["Bangalore"], remote: true, hiring: true, salary: "₹12-40 LPA", culture: 3.5, wlb: 3.2, interview: 3.5, careers: "https://bigbasket.com/careers", employees: "3K+", founded: 2011, tech: ["Python", "React", "Node.js", "AWS"]},
    {name: "Dunzo", type: "PRODUCT", category: "STARTUP", desc: "Hyperlocal delivery", hq: "India", india: ["Bangalore"], remote: true, hiring: false, salary: "₹12-40 LPA", culture: 3.5, wlb: 3.0, interview: 3.5, careers: "https://dunzo.com/careers", employees: "1K+", founded: 2015, tech: ["Python", "React Native", "Node.js", "AWS"]},
    {name: "JioMart", type: "PRODUCT", category: "PRODUCT", desc: "Reliance grocery e-commerce", hq: "India", india: ["Mumbai", "Bangalore"], remote: true, hiring: true, salary: "₹10-35 LPA", culture: 3.5, wlb: 3.5, interview: 3.5, careers: "https://jiomart.com/careers", employees: "5K+", founded: 2020, tech: ["Java", "React", "Python", "AWS"]},
    {name: "Croma", type: "PRODUCT", category: "PRODUCT", desc: "Electronics retail", hq: "India", india: ["Mumbai", "Bangalore"], remote: true, hiring: true, salary: "₹10-35 LPA", culture: 3.5, wlb: 3.8, interview: 3.5, careers: "https://croma.com/careers", employees: "3K+", founded: 2006, tech: ["Java", "React", "SAP"]},
    {name: "Shopee", type: "PRODUCT", category: "BIG_TECH", desc: "SE Asian e-commerce giant", hq: "Singapore", india: ["Bangalore"], remote: true, hiring: false, salary: "₹15-50 LPA", culture: 3.5, wlb: 3.0, interview: 4.0, careers: "https://shopee.com/careers", employees: "30K+", founded: 2015, tech: ["Go", "Python", "React", "AWS"]},
    
    // ==================== MEDIA & ENTERTAINMENT ====================
    {name: "Hotstar (Disney+)", type: "PRODUCT", category: "PRODUCT", desc: "Streaming platform", hq: "India", india: ["Mumbai", "Bangalore"], remote: true, hiring: true, salary: "₹18-55 LPA", culture: 4.0, wlb: 3.5, interview: 4.0, careers: "https://hotstar.com/careers", employees: "2K+", founded: 2015, tech: ["Java", "React", "Python", "AWS"]},
    {name: "Sony LIV", type: "PRODUCT", category: "PRODUCT", desc: "Streaming platform", hq: "India", india: ["Mumbai", "Bangalore"], remote: true, hiring: true, salary: "₹12-40 LPA", culture: 3.8, wlb: 3.8, interview: 3.5, careers: "https://sonyliv.com/careers", employees: "500+", founded: 2013, tech: ["Java", "React", "Python", "AWS"]},
    {name: "Zee5", type: "PRODUCT", category: "PRODUCT", desc: "Streaming platform", hq: "India", india: ["Mumbai", "Bangalore"], remote: true, hiring: true, salary: "₹12-40 LPA", culture: 3.5, wlb: 3.5, interview: 3.5, careers: "https://zee5.com/careers", employees: "1K+", founded: 2018, tech: ["Java", "React", "Python", "AWS"]},
    {name: "Jio Cinema", type: "PRODUCT", category: "PRODUCT", desc: "Streaming by Reliance", hq: "India", india: ["Mumbai", "Bangalore"], remote: true, hiring: true, salary: "₹12-40 LPA", culture: 3.5, wlb: 3.5, interview: 3.5, careers: "https://jiocinema.com/careers", employees: "1K+", founded: 2016, tech: ["Java", "React", "Python", "AWS"]},
    {name: "ShareChat", type: "PRODUCT", category: "INDIAN_UNICORN", desc: "Regional social media", hq: "India", india: ["Bangalore"], remote: true, hiring: true, salary: "₹18-55 LPA", culture: 4.0, wlb: 3.5, interview: 4.0, careers: "https://sharechat.com/careers", employees: "2K+", founded: 2015, tech: ["Python", "Go", "React", "ML"]},
    {name: "Koo", type: "PRODUCT", category: "STARTUP", desc: "Indian microblogging", hq: "India", india: ["Bangalore"], remote: true, hiring: false, salary: "₹12-40 LPA", culture: 3.5, wlb: 3.5, interview: 3.5, careers: "https://kooapp.com/careers", employees: "300+", founded: 2020, tech: ["Python", "React", "Node.js", "AWS"]},
];

// Export
if (typeof window !== 'undefined') {
    window.COMPANIES_DATABASE_2 = COMPANIES_DATABASE_2;
}


