// Comprehensive Companies Database for AI Spectrum India
// 200+ Companies across all sectors

const COMPANIES_DATABASE = [
    // ==================== FAANG / Big Tech ====================
    {name: "Google", type: "PRODUCT", category: "FAANG", desc: "World's leading search and cloud company", hq: "USA", india: ["Bangalore", "Hyderabad", "Gurgaon", "Mumbai"], remote: true, hiring: true, salary: "₹25-80 LPA", culture: 4.5, wlb: 4.2, interview: 4.5, careers: "https://careers.google.com", glassdoor: "https://glassdoor.com/google", employees: "180K+", founded: 1998, tech: ["Python", "Go", "Java", "C++", "TensorFlow"]},
    {name: "Microsoft", type: "PRODUCT", category: "FAANG", desc: "Enterprise software and cloud leader", hq: "USA", india: ["Bangalore", "Hyderabad", "Noida", "Pune"], remote: true, hiring: true, salary: "₹20-70 LPA", culture: 4.3, wlb: 4.0, interview: 4.3, careers: "https://careers.microsoft.com", glassdoor: "https://glassdoor.com/microsoft", employees: "220K+", founded: 1975, tech: ["C#", ".NET", "Azure", "TypeScript", "Python"]},
    {name: "Amazon", type: "PRODUCT", category: "FAANG", desc: "E-commerce and cloud computing giant", hq: "USA", india: ["Bangalore", "Hyderabad", "Chennai", "Delhi", "Pune"], remote: true, hiring: true, salary: "₹20-75 LPA", culture: 3.8, wlb: 3.2, interview: 4.5, careers: "https://amazon.jobs", glassdoor: "https://glassdoor.com/amazon", employees: "1.5M+", founded: 1994, tech: ["Java", "Python", "AWS", "React", "Node.js"]},
    {name: "Meta (Facebook)", type: "PRODUCT", category: "FAANG", desc: "Social media and VR technology company", hq: "USA", india: ["Bangalore", "Hyderabad", "Gurgaon"], remote: true, hiring: true, salary: "₹30-90 LPA", culture: 4.2, wlb: 3.8, interview: 4.6, careers: "https://metacareers.com", glassdoor: "https://glassdoor.com/meta", employees: "70K+", founded: 2004, tech: ["React", "Python", "C++", "Hack", "GraphQL"]},
    {name: "Apple", type: "PRODUCT", category: "FAANG", desc: "Consumer electronics and software", hq: "USA", india: ["Bangalore", "Hyderabad"], remote: false, hiring: true, salary: "₹25-80 LPA", culture: 4.4, wlb: 3.9, interview: 4.4, careers: "https://apple.com/careers", glassdoor: "https://glassdoor.com/apple", employees: "160K+", founded: 1976, tech: ["Swift", "Objective-C", "Python", "ML"]},
    {name: "Netflix", type: "PRODUCT", category: "FAANG", desc: "Streaming entertainment service", hq: "USA", india: ["Mumbai"], remote: true, hiring: true, salary: "₹40-100 LPA", culture: 4.5, wlb: 4.0, interview: 4.5, careers: "https://jobs.netflix.com", glassdoor: "https://glassdoor.com/netflix", employees: "12K+", founded: 1997, tech: ["Java", "Python", "Node.js", "React"]},
    
    // ==================== Other Big Tech ====================
    {name: "Uber", type: "PRODUCT", category: "BIG_TECH", desc: "Ride-sharing and delivery platform", hq: "USA", india: ["Bangalore", "Hyderabad"], remote: true, hiring: true, salary: "₹25-70 LPA", culture: 4.0, wlb: 3.5, interview: 4.3, careers: "https://uber.com/careers", glassdoor: "https://glassdoor.com/uber", employees: "30K+", founded: 2009, tech: ["Go", "Python", "Java", "React"]},
    {name: "Airbnb", type: "PRODUCT", category: "BIG_TECH", desc: "Online accommodation marketplace", hq: "USA", india: ["Bangalore"], remote: true, hiring: true, salary: "₹30-80 LPA", culture: 4.4, wlb: 4.2, interview: 4.2, careers: "https://careers.airbnb.com", glassdoor: "https://glassdoor.com/airbnb", employees: "6K+", founded: 2008, tech: ["Ruby", "React", "Java", "Kotlin"]},
    {name: "Salesforce", type: "PRODUCT", category: "BIG_TECH", desc: "CRM and enterprise cloud", hq: "USA", india: ["Bangalore", "Hyderabad", "Mumbai"], remote: true, hiring: true, salary: "₹18-55 LPA", culture: 4.3, wlb: 4.0, interview: 3.8, careers: "https://salesforce.com/careers", glassdoor: "https://glassdoor.com/salesforce", employees: "70K+", founded: 1999, tech: ["Java", "Apex", "Lightning", "Python"]},
    {name: "Adobe", type: "PRODUCT", category: "BIG_TECH", desc: "Creative software and digital marketing", hq: "USA", india: ["Bangalore", "Noida"], remote: true, hiring: true, salary: "₹18-60 LPA", culture: 4.2, wlb: 4.1, interview: 4.0, careers: "https://adobe.com/careers", glassdoor: "https://glassdoor.com/adobe", employees: "29K+", founded: 1982, tech: ["C++", "JavaScript", "Python", "React"]},
    {name: "Oracle", type: "PRODUCT", category: "BIG_TECH", desc: "Enterprise database and cloud", hq: "USA", india: ["Bangalore", "Hyderabad", "Mumbai", "Pune", "Delhi"], remote: true, hiring: true, salary: "₹12-45 LPA", culture: 3.8, wlb: 3.8, interview: 3.8, careers: "https://oracle.com/careers", glassdoor: "https://glassdoor.com/oracle", employees: "143K+", founded: 1977, tech: ["Java", "PL/SQL", "Cloud", "Python"]},
    {name: "LinkedIn", type: "PRODUCT", category: "BIG_TECH", desc: "Professional networking platform", hq: "USA", india: ["Bangalore"], remote: true, hiring: true, salary: "₹25-70 LPA", culture: 4.3, wlb: 4.2, interview: 4.2, careers: "https://careers.linkedin.com", glassdoor: "https://glassdoor.com/linkedin", employees: "20K+", founded: 2002, tech: ["Java", "Scala", "Python", "React"]},
    {name: "Twitter/X", type: "PRODUCT", category: "BIG_TECH", desc: "Social media platform", hq: "USA", india: ["Bangalore"], remote: true, hiring: false, salary: "₹25-70 LPA", culture: 3.5, wlb: 3.5, interview: 4.2, careers: "https://careers.twitter.com", glassdoor: "https://glassdoor.com/twitter", employees: "1.5K+", founded: 2006, tech: ["Scala", "Java", "Python", "GraphQL"]},
    {name: "Stripe", type: "PRODUCT", category: "UNICORN", desc: "Online payment processing", hq: "USA", india: ["Bangalore"], remote: true, hiring: true, salary: "₹35-90 LPA", culture: 4.5, wlb: 4.0, interview: 4.5, careers: "https://stripe.com/jobs", glassdoor: "https://glassdoor.com/stripe", employees: "8K+", founded: 2010, tech: ["Ruby", "Go", "React", "TypeScript"]},
    {name: "Spotify", type: "PRODUCT", category: "BIG_TECH", desc: "Music streaming platform", hq: "Sweden", india: ["Mumbai"], remote: true, hiring: true, salary: "₹30-70 LPA", culture: 4.4, wlb: 4.3, interview: 4.0, careers: "https://spotify.com/jobs", glassdoor: "https://glassdoor.com/spotify", employees: "9K+", founded: 2006, tech: ["Python", "Java", "React", "GCP"]},
    
    // ==================== Indian Unicorns ====================
    {name: "Flipkart", type: "PRODUCT", category: "INDIAN_UNICORN", desc: "India's largest e-commerce platform", hq: "India", india: ["Bangalore"], remote: true, hiring: true, salary: "₹20-60 LPA", culture: 4.0, wlb: 3.5, interview: 4.2, careers: "https://flipkartcareers.com", glassdoor: "https://glassdoor.com/flipkart", employees: "40K+", founded: 2007, tech: ["Java", "React", "Python", "Node.js"]},
    {name: "Razorpay", type: "PRODUCT", category: "INDIAN_UNICORN", desc: "Payment gateway and fintech", hq: "India", india: ["Bangalore"], remote: true, hiring: true, salary: "₹18-55 LPA", culture: 4.3, wlb: 3.8, interview: 4.0, careers: "https://razorpay.com/jobs", glassdoor: "https://glassdoor.com/razorpay", employees: "3K+", founded: 2014, tech: ["Go", "Ruby", "React", "Python"]},
    {name: "Zerodha", type: "PRODUCT", category: "INDIAN_UNICORN", desc: "India's largest stock broker", hq: "India", india: ["Bangalore"], remote: true, hiring: true, salary: "₹15-50 LPA", culture: 4.5, wlb: 4.5, interview: 4.0, careers: "https://zerodha.com/careers", glassdoor: "https://glassdoor.com/zerodha", employees: "1.5K+", founded: 2010, tech: ["Go", "Python", "React", "PostgreSQL"]},
    {name: "CRED", type: "PRODUCT", category: "INDIAN_UNICORN", desc: "Credit card payments app", hq: "India", india: ["Bangalore"], remote: true, hiring: true, salary: "₹25-70 LPA", culture: 4.2, wlb: 3.5, interview: 4.3, careers: "https://cred.club/careers", glassdoor: "https://glassdoor.com/cred", employees: "1K+", founded: 2018, tech: ["Kotlin", "Swift", "Node.js", "Python"]},
    {name: "PhonePe", type: "PRODUCT", category: "INDIAN_UNICORN", desc: "Digital payments platform", hq: "India", india: ["Bangalore", "Pune"], remote: true, hiring: true, salary: "₹18-55 LPA", culture: 4.0, wlb: 3.5, interview: 4.0, careers: "https://phonepe.com/careers", glassdoor: "https://glassdoor.com/phonepe", employees: "5K+", founded: 2015, tech: ["Java", "Kotlin", "React Native", "Python"]},
    {name: "Swiggy", type: "PRODUCT", category: "INDIAN_UNICORN", desc: "Food delivery platform", hq: "India", india: ["Bangalore", "Hyderabad"], remote: true, hiring: true, salary: "₹18-55 LPA", culture: 3.8, wlb: 3.2, interview: 4.0, careers: "https://swiggy.com/careers", glassdoor: "https://glassdoor.com/swiggy", employees: "5K+", founded: 2014, tech: ["Python", "Java", "React", "Go"]},
    {name: "Zomato", type: "PRODUCT", category: "INDIAN_UNICORN", desc: "Food delivery and restaurant discovery", hq: "India", india: ["Gurgaon", "Bangalore"], remote: true, hiring: true, salary: "₹15-50 LPA", culture: 3.8, wlb: 3.3, interview: 3.8, careers: "https://zomato.com/careers", glassdoor: "https://glassdoor.com/zomato", employees: "4K+", founded: 2008, tech: ["Python", "PHP", "React", "AWS"]},
    {name: "Ola", type: "PRODUCT", category: "INDIAN_UNICORN", desc: "Ride-hailing and electric vehicles", hq: "India", india: ["Bangalore"], remote: true, hiring: true, salary: "₹15-50 LPA", culture: 3.5, wlb: 3.2, interview: 3.8, careers: "https://ola.com/careers", glassdoor: "https://glassdoor.com/olacabs", employees: "8K+", founded: 2010, tech: ["Java", "Python", "Kotlin", "React"]},
    {name: "Paytm", type: "PRODUCT", category: "INDIAN_UNICORN", desc: "Digital payments and fintech", hq: "India", india: ["Noida", "Bangalore", "Pune"], remote: true, hiring: true, salary: "₹12-45 LPA", culture: 3.5, wlb: 3.0, interview: 3.5, careers: "https://paytm.com/careers", glassdoor: "https://glassdoor.com/paytm", employees: "10K+", founded: 2010, tech: ["Java", "Python", "React", "Node.js"]},
    {name: "Groww", type: "PRODUCT", category: "INDIAN_UNICORN", desc: "Investment and trading platform", hq: "India", india: ["Bangalore"], remote: true, hiring: true, salary: "₹20-55 LPA", culture: 4.2, wlb: 3.8, interview: 4.0, careers: "https://groww.in/careers", glassdoor: "https://glassdoor.com/groww", employees: "1K+", founded: 2016, tech: ["Java", "Kotlin", "React", "Python"]},
    {name: "Meesho", type: "PRODUCT", category: "INDIAN_UNICORN", desc: "Social commerce platform", hq: "India", india: ["Bangalore"], remote: true, hiring: true, salary: "₹18-55 LPA", culture: 4.0, wlb: 3.5, interview: 4.0, careers: "https://meesho.com/careers", glassdoor: "https://glassdoor.com/meesho", employees: "2K+", founded: 2015, tech: ["Python", "Java", "React", "AWS"]},
    {name: "Dream11", type: "PRODUCT", category: "INDIAN_UNICORN", desc: "Fantasy sports platform", hq: "India", india: ["Mumbai"], remote: true, hiring: true, salary: "₹20-60 LPA", culture: 4.0, wlb: 3.8, interview: 4.2, careers: "https://dreamsports.group/careers", glassdoor: "https://glassdoor.com/dream11", employees: "1.5K+", founded: 2008, tech: ["Java", "React", "Python", "AWS"]},
    {name: "Chargebee", type: "PRODUCT", category: "INDIAN_UNICORN", desc: "Subscription billing platform", hq: "India", india: ["Chennai"], remote: true, hiring: true, salary: "₹18-50 LPA", culture: 4.3, wlb: 4.0, interview: 3.8, careers: "https://chargebee.com/careers", glassdoor: "https://glassdoor.com/chargebee", employees: "1K+", founded: 2011, tech: ["Ruby", "React", "Python", "AWS"]},
    {name: "Postman", type: "PRODUCT", category: "INDIAN_UNICORN", desc: "API development platform", hq: "India", india: ["Bangalore"], remote: true, hiring: true, salary: "₹20-60 LPA", culture: 4.4, wlb: 4.2, interview: 4.0, careers: "https://postman.com/careers", glassdoor: "https://glassdoor.com/postman", employees: "800+", founded: 2014, tech: ["Node.js", "React", "Go", "Electron"]},
    {name: "Freshworks", type: "PRODUCT", category: "INDIAN_UNICORN", desc: "SaaS for customer engagement", hq: "India", india: ["Chennai", "Bangalore"], remote: true, hiring: true, salary: "₹15-50 LPA", culture: 4.0, wlb: 3.8, interview: 3.8, careers: "https://freshworks.com/careers", glassdoor: "https://glassdoor.com/freshworks", employees: "5K+", founded: 2010, tech: ["Ruby", "Python", "React", "AWS"]},
    {name: "Browserstack", type: "PRODUCT", category: "INDIAN_UNICORN", desc: "Browser testing platform", hq: "India", india: ["Mumbai"], remote: true, hiring: true, salary: "₹20-55 LPA", culture: 4.3, wlb: 4.0, interview: 4.0, careers: "https://browserstack.com/careers", glassdoor: "https://glassdoor.com/browserstack", employees: "800+", founded: 2011, tech: ["Java", "Python", "React", "Selenium"]},
    {name: "Licious", type: "PRODUCT", category: "INDIAN_UNICORN", desc: "Fresh meat and seafood delivery", hq: "India", india: ["Bangalore"], remote: true, hiring: true, salary: "₹15-45 LPA", culture: 3.8, wlb: 3.5, interview: 3.5, careers: "https://licious.in/careers", glassdoor: "https://glassdoor.com/licious", employees: "2K+", founded: 2015, tech: ["Python", "React", "Node.js", "AWS"]},
    {name: "Urban Company", type: "PRODUCT", category: "INDIAN_UNICORN", desc: "Home services platform", hq: "India", india: ["Gurgaon", "Bangalore"], remote: true, hiring: true, salary: "₹15-50 LPA", culture: 3.8, wlb: 3.5, interview: 3.8, careers: "https://urbancompany.com/careers", glassdoor: "https://glassdoor.com/urbancompany", employees: "2K+", founded: 2014, tech: ["Python", "React Native", "Node.js", "AWS"]},
    {name: "Unacademy", type: "PRODUCT", category: "INDIAN_UNICORN", desc: "Online learning platform", hq: "India", india: ["Bangalore"], remote: true, hiring: false, salary: "₹15-50 LPA", culture: 3.5, wlb: 3.0, interview: 3.5, careers: "https://unacademy.com/careers", glassdoor: "https://glassdoor.com/unacademy", employees: "4K+", founded: 2015, tech: ["Python", "React", "Node.js", "AWS"]},
    {name: "Byju's", type: "PRODUCT", category: "INDIAN_UNICORN", desc: "Ed-tech platform", hq: "India", india: ["Bangalore"], remote: true, hiring: false, salary: "₹12-40 LPA", culture: 3.0, wlb: 2.5, interview: 3.0, careers: "https://byjus.com/careers", glassdoor: "https://glassdoor.com/byjus", employees: "10K+", founded: 2011, tech: ["Java", "Python", "React", "AWS"]},
    
    // ==================== IT Services ====================
    {name: "TCS", type: "SERVICE", category: "IT_SERVICES", desc: "India's largest IT services company", hq: "India", india: ["Mumbai", "Bangalore", "Chennai", "Hyderabad", "Pune", "Delhi", "Kolkata"], remote: true, hiring: true, salary: "₹3.5-25 LPA", culture: 3.5, wlb: 3.8, interview: 3.0, careers: "https://tcs.com/careers", glassdoor: "https://glassdoor.com/tcs", employees: "600K+", founded: 1968, tech: ["Java", ".NET", "Python", "SAP", "Cloud"]},
    {name: "Infosys", type: "SERVICE", category: "IT_SERVICES", desc: "Global IT consulting and services", hq: "India", india: ["Bangalore", "Pune", "Hyderabad", "Chennai", "Mysore"], remote: true, hiring: true, salary: "₹3.5-25 LPA", culture: 3.5, wlb: 3.8, interview: 3.2, careers: "https://infosys.com/careers", glassdoor: "https://glassdoor.com/infosys", employees: "350K+", founded: 1981, tech: ["Java", ".NET", "Python", "SAP", "Cloud"]},
    {name: "Wipro", type: "SERVICE", category: "IT_SERVICES", desc: "IT services and consulting", hq: "India", india: ["Bangalore", "Hyderabad", "Chennai", "Pune", "Delhi"], remote: true, hiring: true, salary: "₹3.5-22 LPA", culture: 3.3, wlb: 3.7, interview: 3.0, careers: "https://wipro.com/careers", glassdoor: "https://glassdoor.com/wipro", employees: "250K+", founded: 1945, tech: ["Java", ".NET", "Python", "SAP", "Cloud"]},
    {name: "HCL Technologies", type: "SERVICE", category: "IT_SERVICES", desc: "IT services and engineering", hq: "India", india: ["Noida", "Chennai", "Bangalore", "Hyderabad"], remote: true, hiring: true, salary: "₹4-25 LPA", culture: 3.5, wlb: 3.6, interview: 3.2, careers: "https://hcltech.com/careers", glassdoor: "https://glassdoor.com/hcl-technologies", employees: "220K+", founded: 1976, tech: ["Java", ".NET", "Python", "Cloud", "SAP"]},
    {name: "Tech Mahindra", type: "SERVICE", category: "IT_SERVICES", desc: "IT services and telecom solutions", hq: "India", india: ["Pune", "Hyderabad", "Chennai", "Bangalore"], remote: true, hiring: true, salary: "₹4-22 LPA", culture: 3.4, wlb: 3.5, interview: 3.0, careers: "https://techmahindra.com/careers", glassdoor: "https://glassdoor.com/tech-mahindra", employees: "150K+", founded: 1986, tech: ["Java", ".NET", "5G", "Cloud", "AI"]},
    {name: "Cognizant", type: "SERVICE", category: "IT_SERVICES", desc: "IT services and digital solutions", hq: "USA", india: ["Chennai", "Bangalore", "Hyderabad", "Pune", "Kolkata"], remote: true, hiring: true, salary: "₹4-28 LPA", culture: 3.5, wlb: 3.5, interview: 3.2, careers: "https://cognizant.com/careers", glassdoor: "https://glassdoor.com/cognizant", employees: "350K+", founded: 1994, tech: ["Java", ".NET", "Python", "Cloud", "AI"]},
    {name: "Capgemini", type: "SERVICE", category: "IT_SERVICES", desc: "Global consulting and IT services", hq: "France", india: ["Mumbai", "Bangalore", "Chennai", "Hyderabad", "Pune"], remote: true, hiring: true, salary: "₹5-30 LPA", culture: 3.6, wlb: 3.5, interview: 3.3, careers: "https://capgemini.com/careers", glassdoor: "https://glassdoor.com/capgemini", employees: "350K+", founded: 1967, tech: ["Java", ".NET", "Python", "Cloud", "SAP"]},
    {name: "Accenture", type: "SERVICE", category: "IT_SERVICES", desc: "Global consulting and professional services", hq: "Ireland", india: ["Bangalore", "Mumbai", "Chennai", "Hyderabad", "Pune", "Delhi"], remote: true, hiring: true, salary: "₹5-35 LPA", culture: 3.7, wlb: 3.3, interview: 3.5, careers: "https://accenture.com/careers", glassdoor: "https://glassdoor.com/accenture", employees: "700K+", founded: 1989, tech: ["Java", ".NET", "Cloud", "AI", "Salesforce"]},
    {name: "IBM", type: "SERVICE", category: "IT_SERVICES", desc: "Enterprise technology and consulting", hq: "USA", india: ["Bangalore", "Hyderabad", "Pune", "Delhi", "Kolkata"], remote: true, hiring: true, salary: "₹6-35 LPA", culture: 3.6, wlb: 3.8, interview: 3.5, careers: "https://ibm.com/careers", glassdoor: "https://glassdoor.com/ibm", employees: "280K+", founded: 1911, tech: ["Java", "Python", "Cloud", "AI", "Watson"]},
    {name: "Deloitte", type: "SERVICE", category: "CONSULTING", desc: "Professional services and consulting", hq: "UK", india: ["Mumbai", "Bangalore", "Hyderabad", "Chennai", "Delhi"], remote: true, hiring: true, salary: "₹8-40 LPA", culture: 3.8, wlb: 3.2, interview: 3.8, careers: "https://deloitte.com/careers", glassdoor: "https://glassdoor.com/deloitte", employees: "400K+", founded: 1845, tech: ["SAP", "Salesforce", "Cloud", "Analytics"]},
    {name: "EY (Ernst & Young)", type: "SERVICE", category: "CONSULTING", desc: "Professional services firm", hq: "UK", india: ["Mumbai", "Bangalore", "Delhi", "Chennai", "Hyderabad"], remote: true, hiring: true, salary: "₹7-35 LPA", culture: 3.7, wlb: 3.2, interview: 3.6, careers: "https://ey.com/careers", glassdoor: "https://glassdoor.com/ey", employees: "365K+", founded: 1989, tech: ["SAP", "Data Analytics", "Cloud", "RPA"]},
    {name: "PwC", type: "SERVICE", category: "CONSULTING", desc: "Professional services network", hq: "UK", india: ["Mumbai", "Bangalore", "Delhi", "Kolkata"], remote: true, hiring: true, salary: "₹8-38 LPA", culture: 3.7, wlb: 3.0, interview: 3.7, careers: "https://pwc.com/careers", glassdoor: "https://glassdoor.com/pwc", employees: "328K+", founded: 1998, tech: ["SAP", "Salesforce", "Data Analytics", "Cloud"]},
    {name: "KPMG", type: "SERVICE", category: "CONSULTING", desc: "Professional services firm", hq: "Netherlands", india: ["Mumbai", "Delhi", "Bangalore", "Chennai"], remote: true, hiring: true, salary: "₹7-35 LPA", culture: 3.6, wlb: 3.0, interview: 3.5, careers: "https://kpmg.com/careers", glassdoor: "https://glassdoor.com/kpmg", employees: "265K+", founded: 1987, tech: ["SAP", "Data Analytics", "Cloud", "Cyber"]},
    
    // ==================== Startups & Others ====================
    {name: "Atlassian", type: "PRODUCT", category: "BIG_TECH", desc: "Team collaboration software", hq: "Australia", india: ["Bangalore"], remote: true, hiring: true, salary: "₹25-70 LPA", culture: 4.5, wlb: 4.3, interview: 4.0, careers: "https://atlassian.com/careers", glassdoor: "https://glassdoor.com/atlassian", employees: "10K+", founded: 2002, tech: ["Java", "Python", "React", "AWS"]},
    {name: "Shopify", type: "PRODUCT", category: "BIG_TECH", desc: "E-commerce platform", hq: "Canada", india: ["Bangalore"], remote: true, hiring: true, salary: "₹25-65 LPA", culture: 4.3, wlb: 4.2, interview: 4.0, careers: "https://shopify.com/careers", glassdoor: "https://glassdoor.com/shopify", employees: "10K+", founded: 2006, tech: ["Ruby", "React", "Go", "Python"]},
    {name: "Slack", type: "PRODUCT", category: "BIG_TECH", desc: "Workplace messaging platform", hq: "USA", india: ["Pune"], remote: true, hiring: true, salary: "₹25-65 LPA", culture: 4.4, wlb: 4.2, interview: 4.0, careers: "https://slack.com/careers", glassdoor: "https://glassdoor.com/slack", employees: "3K+", founded: 2009, tech: ["Java", "React", "Go", "AWS"]},
    {name: "Twilio", type: "PRODUCT", category: "BIG_TECH", desc: "Cloud communications platform", hq: "USA", india: ["Bangalore"], remote: true, hiring: true, salary: "₹22-60 LPA", culture: 4.2, wlb: 4.0, interview: 3.8, careers: "https://twilio.com/careers", glassdoor: "https://glassdoor.com/twilio", employees: "8K+", founded: 2008, tech: ["Java", "Python", "Node.js", "AWS"]},
    {name: "Notion", type: "PRODUCT", category: "STARTUP", desc: "All-in-one workspace", hq: "USA", india: ["Remote"], remote: true, hiring: true, salary: "₹30-80 LPA", culture: 4.6, wlb: 4.3, interview: 4.2, careers: "https://notion.so/careers", glassdoor: "https://glassdoor.com/notion", employees: "500+", founded: 2016, tech: ["TypeScript", "React", "Kotlin", "PostgreSQL"]},
    {name: "Figma", type: "PRODUCT", category: "STARTUP", desc: "Collaborative design tool", hq: "USA", india: ["Remote"], remote: true, hiring: true, salary: "₹30-80 LPA", culture: 4.5, wlb: 4.2, interview: 4.3, careers: "https://figma.com/careers", glassdoor: "https://glassdoor.com/figma", employees: "1K+", founded: 2012, tech: ["C++", "TypeScript", "WebGL", "Rust"]},
    {name: "Canva", type: "PRODUCT", category: "UNICORN", desc: "Online design platform", hq: "Australia", india: ["Remote"], remote: true, hiring: true, salary: "₹25-65 LPA", culture: 4.4, wlb: 4.3, interview: 4.0, careers: "https://canva.com/careers", glassdoor: "https://glassdoor.com/canva", employees: "4K+", founded: 2012, tech: ["Java", "Python", "React", "AWS"]},
    {name: "Databricks", type: "PRODUCT", category: "UNICORN", desc: "Data and AI platform", hq: "USA", india: ["Bangalore"], remote: true, hiring: true, salary: "₹35-90 LPA", culture: 4.4, wlb: 4.0, interview: 4.5, careers: "https://databricks.com/careers", glassdoor: "https://glassdoor.com/databricks", employees: "5K+", founded: 2013, tech: ["Scala", "Python", "Spark", "Delta Lake"]},
    {name: "Snowflake", type: "PRODUCT", category: "UNICORN", desc: "Cloud data platform", hq: "USA", india: ["Bangalore"], remote: true, hiring: true, salary: "₹30-80 LPA", culture: 4.3, wlb: 4.0, interview: 4.3, careers: "https://snowflake.com/careers", glassdoor: "https://glassdoor.com/snowflake", employees: "6K+", founded: 2012, tech: ["Java", "Python", "SQL", "Cloud"]},
    {name: "Datadog", type: "PRODUCT", category: "UNICORN", desc: "Monitoring and analytics platform", hq: "USA", india: ["Remote"], remote: true, hiring: true, salary: "₹25-70 LPA", culture: 4.2, wlb: 4.0, interview: 4.0, careers: "https://datadoghq.com/careers", glassdoor: "https://glassdoor.com/datadog", employees: "5K+", founded: 2010, tech: ["Go", "Python", "React", "Kubernetes"]},
    {name: "HashiCorp", type: "PRODUCT", category: "UNICORN", desc: "Infrastructure automation", hq: "USA", india: ["Bangalore"], remote: true, hiring: true, salary: "₹25-70 LPA", culture: 4.4, wlb: 4.2, interview: 4.0, careers: "https://hashicorp.com/careers", glassdoor: "https://glassdoor.com/hashicorp", employees: "2K+", founded: 2012, tech: ["Go", "Terraform", "Vault", "Consul"]},
    {name: "Confluent", type: "PRODUCT", category: "UNICORN", desc: "Data streaming platform", hq: "USA", india: ["Bangalore"], remote: true, hiring: true, salary: "₹25-70 LPA", culture: 4.3, wlb: 4.0, interview: 4.2, careers: "https://confluent.io/careers", glassdoor: "https://glassdoor.com/confluent", employees: "3K+", founded: 2014, tech: ["Java", "Kafka", "Python", "Go"]},
    {name: "MongoDB", type: "PRODUCT", category: "UNICORN", desc: "Database platform", hq: "USA", india: ["Gurgaon", "Bangalore"], remote: true, hiring: true, salary: "₹22-65 LPA", culture: 4.2, wlb: 4.0, interview: 4.0, careers: "https://mongodb.com/careers", glassdoor: "https://glassdoor.com/mongodb", employees: "5K+", founded: 2007, tech: ["C++", "Go", "Python", "JavaScript"]},
    {name: "Elastic", type: "PRODUCT", category: "UNICORN", desc: "Search and analytics platform", hq: "Netherlands", india: ["Bangalore", "Hyderabad"], remote: true, hiring: true, salary: "₹22-60 LPA", culture: 4.2, wlb: 4.2, interview: 3.8, careers: "https://elastic.co/careers", glassdoor: "https://glassdoor.com/elastic", employees: "3K+", founded: 2012, tech: ["Java", "Go", "Elasticsearch", "Kibana"]},
    {name: "Vercel", type: "PRODUCT", category: "STARTUP", desc: "Frontend cloud platform", hq: "USA", india: ["Remote"], remote: true, hiring: true, salary: "₹30-75 LPA", culture: 4.5, wlb: 4.3, interview: 4.2, careers: "https://vercel.com/careers", glassdoor: "https://glassdoor.com/vercel", employees: "500+", founded: 2015, tech: ["TypeScript", "Next.js", "React", "Go"]},
    {name: "Supabase", type: "PRODUCT", category: "STARTUP", desc: "Open source Firebase alternative", hq: "USA", india: ["Remote"], remote: true, hiring: true, salary: "₹25-65 LPA", culture: 4.5, wlb: 4.4, interview: 4.0, careers: "https://supabase.com/careers", glassdoor: "https://glassdoor.com/supabase", employees: "200+", founded: 2020, tech: ["PostgreSQL", "TypeScript", "Go", "Elixir"]},
    {name: "Linear", type: "PRODUCT", category: "STARTUP", desc: "Issue tracking for modern teams", hq: "USA", india: ["Remote"], remote: true, hiring: true, salary: "₹30-70 LPA", culture: 4.6, wlb: 4.5, interview: 4.2, careers: "https://linear.app/careers", glassdoor: "https://glassdoor.com/linear", employees: "100+", founded: 2019, tech: ["TypeScript", "React", "Node.js", "PostgreSQL"]},
];

// Export
if (typeof window !== 'undefined') {
    window.COMPANIES_DATABASE = COMPANIES_DATABASE;
}


