// Extended Companies Database - Part 3
// More IT Services, Consulting, Healthcare, Finance & Fintech

const COMPANIES_DATABASE_3 = [
    // ==================== MORE IT SERVICES ====================
    {name: "L&T Infotech (LTIMindtree)", type: "SERVICE", category: "IT_SERVICES", desc: "IT services and digital solutions", hq: "India", india: ["Mumbai", "Bangalore", "Chennai", "Pune", "Hyderabad"], remote: true, hiring: true, salary: "₹4-28 LPA", culture: 3.6, wlb: 3.7, interview: 3.3, careers: "https://ltimindtree.com/careers", employees: "90K+", founded: 1997, tech: ["Java", ".NET", "Python", "Cloud", "SAP"]},
    {name: "Mphasis", type: "SERVICE", category: "IT_SERVICES", desc: "IT services and consulting", hq: "India", india: ["Bangalore", "Chennai", "Pune", "Hyderabad"], remote: true, hiring: true, salary: "₹4-25 LPA", culture: 3.5, wlb: 3.7, interview: 3.2, careers: "https://mphasis.com/careers", employees: "35K+", founded: 2000, tech: ["Java", ".NET", "Python", "Cloud"]},
    {name: "Mindtree", type: "SERVICE", category: "IT_SERVICES", desc: "Digital transformation services", hq: "India", india: ["Bangalore", "Chennai", "Pune", "Hyderabad"], remote: true, hiring: true, salary: "₹4-28 LPA", culture: 3.8, wlb: 3.7, interview: 3.3, careers: "https://mindtree.com/careers", employees: "40K+", founded: 1999, tech: ["Java", ".NET", "Python", "Cloud", "AI"]},
    {name: "Hexaware", type: "SERVICE", category: "IT_SERVICES", desc: "IT and BPO services", hq: "India", india: ["Mumbai", "Chennai", "Pune", "Nagpur"], remote: true, hiring: true, salary: "₹4-22 LPA", culture: 3.5, wlb: 3.8, interview: 3.0, careers: "https://hexaware.com/careers", employees: "30K+", founded: 1990, tech: ["Java", ".NET", "Python", "Cloud"]},
    {name: "Cyient", type: "SERVICE", category: "IT_SERVICES", desc: "Engineering and technology solutions", hq: "India", india: ["Hyderabad", "Bangalore", "Pune"], remote: true, hiring: true, salary: "₹4-22 LPA", culture: 3.5, wlb: 3.8, interview: 3.0, careers: "https://cyient.com/careers", employees: "15K+", founded: 1991, tech: ["Java", "C++", "Python", "CAD"]},
    {name: "Persistent Systems", type: "SERVICE", category: "IT_SERVICES", desc: "Product engineering services", hq: "India", india: ["Pune", "Bangalore", "Goa", "Nagpur"], remote: true, hiring: true, salary: "₹5-28 LPA", culture: 3.8, wlb: 3.8, interview: 3.5, careers: "https://persistent.com/careers", employees: "23K+", founded: 1990, tech: ["Java", ".NET", "Python", "Cloud", "Salesforce"]},
    {name: "Coforge", type: "SERVICE", category: "IT_SERVICES", desc: "IT solutions and services", hq: "India", india: ["Noida", "Bangalore", "Hyderabad"], remote: true, hiring: true, salary: "₹5-25 LPA", culture: 3.6, wlb: 3.7, interview: 3.2, careers: "https://coforge.com/careers", employees: "25K+", founded: 1992, tech: ["Java", ".NET", "Python", "Cloud"]},
    {name: "Birlasoft", type: "SERVICE", category: "IT_SERVICES", desc: "Enterprise digital solutions", hq: "India", india: ["Noida", "Pune", "Bangalore"], remote: true, hiring: true, salary: "₹4-22 LPA", culture: 3.5, wlb: 3.7, interview: 3.0, careers: "https://birlasoft.com/careers", employees: "15K+", founded: 1995, tech: ["Java", ".NET", "SAP", "Cloud"]},
    {name: "Zensar", type: "SERVICE", category: "IT_SERVICES", desc: "Digital solutions and technology", hq: "India", india: ["Pune", "Hyderabad", "Bangalore"], remote: true, hiring: true, salary: "₹4-22 LPA", culture: 3.5, wlb: 3.7, interview: 3.0, careers: "https://zensar.com/careers", employees: "12K+", founded: 1991, tech: ["Java", ".NET", "Python", "Cloud"]},
    {name: "LTTS", type: "SERVICE", category: "IT_SERVICES", desc: "Engineering R&D services", hq: "India", india: ["Bangalore", "Mysore", "Pune", "Hyderabad"], remote: true, hiring: true, salary: "₹4-25 LPA", culture: 3.6, wlb: 3.8, interview: 3.3, careers: "https://ltts.com/careers", employees: "22K+", founded: 2006, tech: ["Embedded", "IoT", "AI", "Cloud"]},
    {name: "Tata Elxsi", type: "SERVICE", category: "IT_SERVICES", desc: "Design and technology services", hq: "India", india: ["Bangalore", "Trivandrum", "Pune", "Chennai"], remote: true, hiring: true, salary: "₹5-28 LPA", culture: 3.8, wlb: 3.7, interview: 3.5, careers: "https://tataelxsi.com/careers", employees: "12K+", founded: 1989, tech: ["Embedded", "AI", "Cloud", "Design"]},
    {name: "Happiest Minds", type: "SERVICE", category: "IT_SERVICES", desc: "Digital transformation company", hq: "India", india: ["Bangalore", "Chennai", "Pune"], remote: true, hiring: true, salary: "₹5-25 LPA", culture: 4.0, wlb: 3.8, interview: 3.5, careers: "https://happiestminds.com/careers", employees: "5K+", founded: 2011, tech: ["Cloud", "AI", "IoT", "Security"]},
    {name: "Sonata Software", type: "SERVICE", category: "IT_SERVICES", desc: "IT services and products", hq: "India", india: ["Bangalore", "Hyderabad"], remote: true, hiring: true, salary: "₹4-22 LPA", culture: 3.5, wlb: 3.8, interview: 3.0, careers: "https://sonata-software.com/careers", employees: "6K+", founded: 1989, tech: ["Java", ".NET", "Microsoft", "Cloud"]},
    {name: "Sasken", type: "SERVICE", category: "IT_SERVICES", desc: "Product engineering services", hq: "India", india: ["Bangalore", "Chennai", "Pune"], remote: true, hiring: true, salary: "₹5-25 LPA", culture: 3.6, wlb: 3.8, interview: 3.3, careers: "https://sasken.com/careers", employees: "3K+", founded: 1989, tech: ["Embedded", "5G", "AI", "Automotive"]},
    {name: "Mastek", type: "SERVICE", category: "IT_SERVICES", desc: "Enterprise solutions", hq: "India", india: ["Mumbai", "Pune"], remote: true, hiring: true, salary: "₹4-22 LPA", culture: 3.5, wlb: 3.7, interview: 3.0, careers: "https://mastek.com/careers", employees: "6K+", founded: 1982, tech: ["Java", ".NET", "Oracle", "Cloud"]},
    {name: "KPIT Technologies", type: "SERVICE", category: "IT_SERVICES", desc: "Automotive software", hq: "India", india: ["Pune", "Bangalore"], remote: true, hiring: true, salary: "₹5-28 LPA", culture: 3.7, wlb: 3.7, interview: 3.5, careers: "https://kpit.com/careers", employees: "13K+", founded: 1990, tech: ["Embedded", "Automotive", "AI", "EV"]},
    {name: "Virtusa", type: "SERVICE", category: "IT_SERVICES", desc: "IT consulting services", hq: "USA", india: ["Hyderabad", "Chennai", "Bangalore"], remote: true, hiring: true, salary: "₹5-28 LPA", culture: 3.5, wlb: 3.5, interview: 3.3, careers: "https://virtusa.com/careers", employees: "30K+", founded: 1996, tech: ["Java", ".NET", "Cloud", "AI"]},
    {name: "Mphasis", type: "SERVICE", category: "IT_SERVICES", desc: "IT solutions and services", hq: "India", india: ["Bangalore", "Pune", "Chennai"], remote: true, hiring: true, salary: "₹4-25 LPA", culture: 3.5, wlb: 3.7, interview: 3.2, careers: "https://mphasis.com/careers", employees: "35K+", founded: 2000, tech: ["Java", ".NET", "Cloud", "AI"]},
    {name: "NTT Data", type: "SERVICE", category: "IT_SERVICES", desc: "Global IT services", hq: "Japan", india: ["Bangalore", "Chennai", "Mumbai", "Pune"], remote: true, hiring: true, salary: "₹5-28 LPA", culture: 3.7, wlb: 3.8, interview: 3.3, careers: "https://nttdata.com/careers", employees: "190K+", founded: 1988, tech: ["Java", ".NET", "SAP", "Cloud"]},
    {name: "DXC Technology", type: "SERVICE", category: "IT_SERVICES", desc: "IT services company", hq: "USA", india: ["Bangalore", "Chennai", "Hyderabad"], remote: true, hiring: true, salary: "₹4-25 LPA", culture: 3.3, wlb: 3.5, interview: 3.0, careers: "https://dxc.com/careers", employees: "130K+", founded: 2017, tech: ["Java", ".NET", "Cloud", "SAP"]},
    {name: "Atos", type: "SERVICE", category: "IT_SERVICES", desc: "Digital transformation", hq: "France", india: ["Bangalore", "Chennai", "Pune"], remote: true, hiring: true, salary: "₹5-25 LPA", culture: 3.5, wlb: 3.6, interview: 3.2, careers: "https://atos.net/careers", employees: "110K+", founded: 1997, tech: ["Java", ".NET", "Cloud", "SAP"]},
    {name: "CGI", type: "SERVICE", category: "IT_SERVICES", desc: "IT and business consulting", hq: "Canada", india: ["Bangalore", "Chennai", "Mumbai"], remote: true, hiring: true, salary: "₹5-28 LPA", culture: 3.7, wlb: 3.8, interview: 3.3, careers: "https://cgi.com/careers", employees: "90K+", founded: 1976, tech: ["Java", ".NET", "Cloud", "SAP"]},
    
    // ==================== FINANCE & BANKING TECH ====================
    {name: "Goldman Sachs", type: "PRODUCT", category: "FINANCE", desc: "Investment banking and technology", hq: "USA", india: ["Bangalore", "Hyderabad"], remote: true, hiring: true, salary: "₹25-80 LPA", culture: 4.0, wlb: 3.0, interview: 4.5, careers: "https://goldmansachs.com/careers", employees: "45K+", founded: 1869, tech: ["Java", "Python", "SecDB", "Cloud"]},
    {name: "Morgan Stanley", type: "PRODUCT", category: "FINANCE", desc: "Financial services and technology", hq: "USA", india: ["Mumbai", "Bangalore"], remote: true, hiring: true, salary: "₹22-70 LPA", culture: 4.0, wlb: 3.2, interview: 4.3, careers: "https://morganstanley.com/careers", employees: "80K+", founded: 1935, tech: ["Java", "Python", "React", "Cloud"]},
    {name: "JP Morgan Chase", type: "PRODUCT", category: "FINANCE", desc: "Banking and financial services", hq: "USA", india: ["Mumbai", "Bangalore", "Hyderabad"], remote: true, hiring: true, salary: "₹20-65 LPA", culture: 3.8, wlb: 3.3, interview: 4.2, careers: "https://jpmorgan.com/careers", employees: "270K+", founded: 1799, tech: ["Java", "Python", "React", "Cloud"]},
    {name: "Bank of America", type: "PRODUCT", category: "FINANCE", desc: "Banking and technology", hq: "USA", india: ["Mumbai", "Hyderabad", "Chennai"], remote: true, hiring: true, salary: "₹18-55 LPA", culture: 3.7, wlb: 3.5, interview: 3.8, careers: "https://bankofamerica.com/careers", employees: "210K+", founded: 1904, tech: ["Java", "Python", ".NET", "Cloud"]},
    {name: "Barclays", type: "PRODUCT", category: "FINANCE", desc: "Banking and financial services", hq: "UK", india: ["Pune", "Chennai"], remote: true, hiring: true, salary: "₹15-50 LPA", culture: 3.7, wlb: 3.6, interview: 3.8, careers: "https://barclays.com/careers", employees: "85K+", founded: 1690, tech: ["Java", "Python", "Cloud", "AI"]},
    {name: "HSBC", type: "PRODUCT", category: "FINANCE", desc: "Banking and financial services", hq: "UK", india: ["Pune", "Bangalore", "Hyderabad"], remote: true, hiring: true, salary: "₹12-45 LPA", culture: 3.6, wlb: 3.7, interview: 3.5, careers: "https://hsbc.com/careers", employees: "220K+", founded: 1865, tech: ["Java", "Python", "Cloud", "AI"]},
    {name: "Standard Chartered", type: "PRODUCT", category: "FINANCE", desc: "Banking and financial services", hq: "UK", india: ["Chennai", "Bangalore"], remote: true, hiring: true, salary: "₹12-45 LPA", culture: 3.6, wlb: 3.7, interview: 3.5, careers: "https://sc.com/careers", employees: "85K+", founded: 1853, tech: ["Java", "Python", "Cloud", "AI"]},
    {name: "Citi", type: "PRODUCT", category: "FINANCE", desc: "Financial services", hq: "USA", india: ["Mumbai", "Chennai", "Pune"], remote: true, hiring: true, salary: "₹15-50 LPA", culture: 3.6, wlb: 3.5, interview: 3.8, careers: "https://citi.com/careers", employees: "230K+", founded: 1812, tech: ["Java", "Python", "Cloud", "AI"]},
    {name: "Deutsche Bank", type: "PRODUCT", category: "FINANCE", desc: "Investment banking", hq: "Germany", india: ["Bangalore", "Pune"], remote: true, hiring: true, salary: "₹15-55 LPA", culture: 3.5, wlb: 3.3, interview: 4.0, careers: "https://db.com/careers", employees: "85K+", founded: 1870, tech: ["Java", "Python", "C++", "Cloud"]},
    {name: "Credit Suisse (UBS)", type: "PRODUCT", category: "FINANCE", desc: "Investment banking", hq: "Switzerland", india: ["Pune"], remote: true, hiring: true, salary: "₹18-55 LPA", culture: 3.7, wlb: 3.3, interview: 4.0, careers: "https://ubs.com/careers", employees: "45K+", founded: 1856, tech: ["Java", "Python", "C++", "Cloud"]},
    {name: "BNY Mellon", type: "PRODUCT", category: "FINANCE", desc: "Investment services", hq: "USA", india: ["Pune", "Chennai"], remote: true, hiring: true, salary: "₹12-45 LPA", culture: 3.6, wlb: 3.7, interview: 3.5, careers: "https://bnymellon.com/careers", employees: "50K+", founded: 1784, tech: ["Java", "Python", "Cloud"]},
    {name: "Nomura", type: "PRODUCT", category: "FINANCE", desc: "Investment banking", hq: "Japan", india: ["Mumbai", "Powai"], remote: true, hiring: true, salary: "₹15-50 LPA", culture: 3.6, wlb: 3.5, interview: 3.8, careers: "https://nomura.com/careers", employees: "27K+", founded: 1925, tech: ["Java", "Python", "C++"]},
    {name: "Fidelity", type: "PRODUCT", category: "FINANCE", desc: "Investment management", hq: "USA", india: ["Bangalore", "Chennai"], remote: true, hiring: true, salary: "₹15-50 LPA", culture: 3.8, wlb: 3.8, interview: 3.8, careers: "https://fidelity.com/careers", employees: "60K+", founded: 1946, tech: ["Java", "Python", "React", "Cloud"]},
    {name: "BlackRock", type: "PRODUCT", category: "FINANCE", desc: "Asset management", hq: "USA", india: ["Mumbai", "Gurgaon"], remote: true, hiring: true, salary: "₹20-60 LPA", culture: 4.0, wlb: 3.5, interview: 4.0, careers: "https://blackrock.com/careers", employees: "20K+", founded: 1988, tech: ["Python", "Java", "Aladdin", "Cloud"]},
    {name: "Visa", type: "PRODUCT", category: "FINANCE", desc: "Payment technology", hq: "USA", india: ["Bangalore"], remote: true, hiring: true, salary: "₹18-55 LPA", culture: 4.0, wlb: 4.0, interview: 4.0, careers: "https://visa.com/careers", employees: "26K+", founded: 1958, tech: ["Java", "Python", "Cloud", "Security"]},
    {name: "Mastercard", type: "PRODUCT", category: "FINANCE", desc: "Payment technology", hq: "USA", india: ["Pune", "Gurgaon"], remote: true, hiring: true, salary: "₹18-55 LPA", culture: 4.0, wlb: 4.0, interview: 4.0, careers: "https://mastercard.com/careers", employees: "29K+", founded: 1966, tech: ["Java", "Python", "Cloud", "AI"]},
    {name: "PayPal", type: "PRODUCT", category: "FINANCE", desc: "Digital payments", hq: "USA", india: ["Bangalore", "Chennai"], remote: true, hiring: true, salary: "₹20-60 LPA", culture: 4.0, wlb: 3.8, interview: 4.0, careers: "https://paypal.com/careers", employees: "30K+", founded: 1998, tech: ["Java", "Node.js", "React", "Cloud"]},
    {name: "American Express", type: "PRODUCT", category: "FINANCE", desc: "Financial services", hq: "USA", india: ["Gurgaon", "Bangalore"], remote: true, hiring: true, salary: "₹15-50 LPA", culture: 3.8, wlb: 3.8, interview: 3.8, careers: "https://americanexpress.com/careers", employees: "65K+", founded: 1850, tech: ["Java", "Python", "React", "Cloud"]},
    
    // ==================== HEALTHCARE & PHARMA TECH ====================
    {name: "Philips", type: "PRODUCT", category: "HEALTHCARE", desc: "Health technology", hq: "Netherlands", india: ["Bangalore", "Pune", "Chennai"], remote: true, hiring: true, salary: "₹12-45 LPA", culture: 4.0, wlb: 4.0, interview: 3.8, careers: "https://philips.com/careers", employees: "80K+", founded: 1891, tech: ["Java", "Python", "Cloud", "AI"]},
    {name: "GE Healthcare", type: "PRODUCT", category: "HEALTHCARE", desc: "Medical technology", hq: "USA", india: ["Bangalore"], remote: true, hiring: true, salary: "₹12-45 LPA", culture: 3.8, wlb: 3.8, interview: 3.8, careers: "https://gehealthcare.com/careers", employees: "50K+", founded: 1994, tech: ["Java", "Python", "AI", "Cloud"]},
    {name: "Siemens Healthineers", type: "PRODUCT", category: "HEALTHCARE", desc: "Medical technology", hq: "Germany", india: ["Bangalore"], remote: true, hiring: true, salary: "₹12-45 LPA", culture: 3.8, wlb: 4.0, interview: 3.8, careers: "https://siemens-healthineers.com/careers", employees: "70K+", founded: 2018, tech: ["C++", "Python", "AI", "Cloud"]},
    {name: "Medtronic", type: "PRODUCT", category: "HEALTHCARE", desc: "Medical devices", hq: "Ireland", india: ["Hyderabad"], remote: true, hiring: true, salary: "₹12-40 LPA", culture: 4.0, wlb: 4.0, interview: 3.5, careers: "https://medtronic.com/careers", employees: "90K+", founded: 1949, tech: ["Embedded", "Python", "Cloud"]},
    {name: "Johnson & Johnson", type: "PRODUCT", category: "HEALTHCARE", desc: "Healthcare products", hq: "USA", india: ["Mumbai", "Bangalore"], remote: true, hiring: true, salary: "₹12-40 LPA", culture: 4.0, wlb: 4.0, interview: 3.5, careers: "https://jnj.com/careers", employees: "150K+", founded: 1886, tech: ["Python", "Java", "Cloud", "Data"]},
    {name: "Abbott", type: "PRODUCT", category: "HEALTHCARE", desc: "Healthcare products", hq: "USA", india: ["Mumbai"], remote: true, hiring: true, salary: "₹10-35 LPA", culture: 4.0, wlb: 4.0, interview: 3.5, careers: "https://abbott.com/careers", employees: "115K+", founded: 1888, tech: ["Python", "Java", "Embedded"]},
    {name: "Optum (UnitedHealth)", type: "PRODUCT", category: "HEALTHCARE", desc: "Healthcare technology", hq: "USA", india: ["Hyderabad", "Noida", "Gurgaon"], remote: true, hiring: true, salary: "₹10-40 LPA", culture: 3.7, wlb: 3.7, interview: 3.5, careers: "https://optum.com/careers", employees: "200K+", founded: 2011, tech: ["Java", "Python", "Cloud", "AI"]},
    {name: "Novartis", type: "PRODUCT", category: "HEALTHCARE", desc: "Pharmaceutical company", hq: "Switzerland", india: ["Hyderabad"], remote: true, hiring: true, salary: "₹12-40 LPA", culture: 4.0, wlb: 4.0, interview: 3.5, careers: "https://novartis.com/careers", employees: "100K+", founded: 1996, tech: ["Python", "R", "Cloud", "AI"]},
    {name: "Pfizer", type: "PRODUCT", category: "HEALTHCARE", desc: "Pharmaceutical company", hq: "USA", india: ["Mumbai", "Chennai"], remote: true, hiring: true, salary: "₹12-40 LPA", culture: 4.0, wlb: 4.0, interview: 3.5, careers: "https://pfizer.com/careers", employees: "80K+", founded: 1849, tech: ["Python", "R", "Cloud", "AI"]},
    {name: "Roche", type: "PRODUCT", category: "HEALTHCARE", desc: "Healthcare and diagnostics", hq: "Switzerland", india: ["Mumbai"], remote: true, hiring: true, salary: "₹12-40 LPA", culture: 4.0, wlb: 4.0, interview: 3.5, careers: "https://roche.com/careers", employees: "100K+", founded: 1896, tech: ["Python", "R", "Cloud", "AI"]},
    {name: "AstraZeneca", type: "PRODUCT", category: "HEALTHCARE", desc: "Pharmaceutical company", hq: "UK", india: ["Bangalore", "Chennai"], remote: true, hiring: true, salary: "₹12-40 LPA", culture: 4.0, wlb: 4.0, interview: 3.5, careers: "https://astrazeneca.com/careers", employees: "80K+", founded: 1999, tech: ["Python", "R", "Cloud", "AI"]},
    
    // ==================== AUTOMOTIVE & EV ====================
    {name: "Tesla", type: "PRODUCT", category: "AUTOMOTIVE", desc: "Electric vehicles and energy", hq: "USA", india: ["Remote"], remote: true, hiring: true, salary: "₹25-80 LPA", culture: 3.5, wlb: 2.5, interview: 4.5, careers: "https://tesla.com/careers", employees: "130K+", founded: 2003, tech: ["Python", "C++", "AI", "Embedded"]},
    {name: "Rivian", type: "PRODUCT", category: "AUTOMOTIVE", desc: "Electric vehicles", hq: "USA", india: ["Bangalore"], remote: true, hiring: true, salary: "₹25-70 LPA", culture: 4.0, wlb: 3.5, interview: 4.2, careers: "https://rivian.com/careers", employees: "16K+", founded: 2009, tech: ["Python", "C++", "AI", "Embedded"]},
    {name: "Mercedes-Benz", type: "PRODUCT", category: "AUTOMOTIVE", desc: "Luxury automotive", hq: "Germany", india: ["Bangalore", "Pune"], remote: true, hiring: true, salary: "₹15-55 LPA", culture: 4.0, wlb: 4.0, interview: 4.0, careers: "https://mercedes-benz.com/careers", employees: "170K+", founded: 1926, tech: ["C++", "Python", "Embedded", "AI"]},
    {name: "BMW", type: "PRODUCT", category: "AUTOMOTIVE", desc: "Luxury automotive", hq: "Germany", india: ["Gurgaon", "Pune"], remote: true, hiring: true, salary: "₹15-50 LPA", culture: 4.0, wlb: 4.0, interview: 4.0, careers: "https://bmw.com/careers", employees: "120K+", founded: 1916, tech: ["C++", "Python", "Embedded", "AI"]},
    {name: "Bosch", type: "PRODUCT", category: "AUTOMOTIVE", desc: "Automotive and industrial technology", hq: "Germany", india: ["Bangalore", "Coimbatore", "Pune"], remote: true, hiring: true, salary: "₹8-35 LPA", culture: 4.0, wlb: 4.2, interview: 3.8, careers: "https://bosch.com/careers", employees: "400K+", founded: 1886, tech: ["C++", "Python", "Embedded", "IoT"]},
    {name: "Continental", type: "PRODUCT", category: "AUTOMOTIVE", desc: "Automotive supplier", hq: "Germany", india: ["Bangalore", "Gurgaon"], remote: true, hiring: true, salary: "₹8-35 LPA", culture: 3.8, wlb: 4.0, interview: 3.5, careers: "https://continental.com/careers", employees: "190K+", founded: 1871, tech: ["C++", "Python", "Embedded", "ADAS"]},
    {name: "ZF Friedrichshafen", type: "PRODUCT", category: "AUTOMOTIVE", desc: "Automotive supplier", hq: "Germany", india: ["Hyderabad", "Chennai"], remote: true, hiring: true, salary: "₹8-32 LPA", culture: 3.8, wlb: 4.0, interview: 3.5, careers: "https://zf.com/careers", employees: "150K+", founded: 1915, tech: ["C++", "Python", "Embedded", "ADAS"]},
    {name: "Denso", type: "PRODUCT", category: "AUTOMOTIVE", desc: "Automotive supplier", hq: "Japan", india: ["Gurgaon", "Bangalore"], remote: true, hiring: true, salary: "₹8-30 LPA", culture: 3.8, wlb: 4.0, interview: 3.5, careers: "https://denso.com/careers", employees: "170K+", founded: 1949, tech: ["C++", "Embedded", "IoT"]},
    {name: "Valeo", type: "PRODUCT", category: "AUTOMOTIVE", desc: "Automotive supplier", hq: "France", india: ["Chennai"], remote: true, hiring: true, salary: "₹8-30 LPA", culture: 3.7, wlb: 3.8, interview: 3.5, careers: "https://valeo.com/careers", employees: "110K+", founded: 1923, tech: ["C++", "Embedded", "ADAS"]},
    {name: "Harman", type: "PRODUCT", category: "AUTOMOTIVE", desc: "Connected car technology", hq: "USA", india: ["Bangalore", "Pune"], remote: true, hiring: true, salary: "₹10-40 LPA", culture: 3.8, wlb: 3.8, interview: 3.8, careers: "https://harman.com/careers", employees: "30K+", founded: 1980, tech: ["C++", "Python", "Android", "QNX"]},
    {name: "Aptiv", type: "PRODUCT", category: "AUTOMOTIVE", desc: "Mobility technology", hq: "Ireland", india: ["Bangalore"], remote: true, hiring: true, salary: "₹10-40 LPA", culture: 3.8, wlb: 3.8, interview: 3.8, careers: "https://aptiv.com/careers", employees: "200K+", founded: 1994, tech: ["C++", "Python", "ADAS", "AI"]},
    {name: "Ather Energy", type: "PRODUCT", category: "INDIAN_STARTUP", desc: "Electric scooters", hq: "India", india: ["Bangalore"], remote: true, hiring: true, salary: "₹10-40 LPA", culture: 4.2, wlb: 3.5, interview: 4.0, careers: "https://atherenergy.com/careers", employees: "2K+", founded: 2013, tech: ["Embedded", "Python", "React", "IoT"]},
    {name: "Ola Electric", type: "PRODUCT", category: "INDIAN_UNICORN", desc: "Electric vehicles", hq: "India", india: ["Bangalore"], remote: true, hiring: true, salary: "₹12-45 LPA", culture: 3.5, wlb: 3.0, interview: 3.8, careers: "https://olaelectric.com/careers", employees: "3K+", founded: 2017, tech: ["Embedded", "Python", "AI", "IoT"]},
    {name: "Tata Motors", type: "PRODUCT", category: "AUTOMOTIVE", desc: "Automotive manufacturer", hq: "India", india: ["Pune", "Mumbai", "Jamshedpur"], remote: true, hiring: true, salary: "₹8-35 LPA", culture: 3.8, wlb: 4.0, interview: 3.5, careers: "https://tatamotors.com/careers", employees: "80K+", founded: 1945, tech: ["C++", "Embedded", "SAP", "IoT"]},
    {name: "Mahindra & Mahindra", type: "PRODUCT", category: "AUTOMOTIVE", desc: "Automotive manufacturer", hq: "India", india: ["Mumbai", "Pune", "Chennai"], remote: true, hiring: true, salary: "₹8-35 LPA", culture: 3.8, wlb: 4.0, interview: 3.5, careers: "https://mahindra.com/careers", employees: "250K+", founded: 1945, tech: ["C++", "Embedded", "SAP", "IoT"]},
];

// Export
if (typeof window !== 'undefined') {
    window.COMPANIES_DATABASE_3 = COMPANIES_DATABASE_3;
}


